name: Deploy to DigitalOcean (Prebuilt)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js
        run: npm run build

      # Clean the remote target directory before copying new file s
      - name: Clean remote directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            rm -rf ~/doggroomingspot/*
            mkdir -p ~/doggroomingspot

      - name: Copy build files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          password: ${{ secrets.DO_PASSWORD }}
          source: ".next,public,package.json,package-lock.json,node_modules"
          target: "~/doggroomingspot"

      - name: Restart app via PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd ~/doggroomingspot
            pm2 restart doggroomingspot || pm2 start npm --name "doggroomingspot" -- start
            pm2 save
